### ISSUE TITLE
bug? "too many open files" during long training runs

### ISSUE THREAD

**Issue by alanngnet** [alanngnet/CoverHunterMPS#20]
On MacOS I have seen the fatal error "OSError: [Errno 24] Too many open files" during long training runs. The most recent example was at epoch 38 @ batch size 64 with "Input dataset items: 1596, valid items: 1596".

Do we have some loose ends to tie up somewhere related to closing files after they're not needed?

2024-04-06 21:33:43,923 INFO Start to train for epoch 38
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/alan/projects/CHtunes/tools/train.py", line 329, in <module>
    _main()
  File "/Users/alan/projects/CHtunes/tools/train.py", line 217, in _main
    step = train_one_epoch(
           ^^^^^^^^^^^^^^^^
  File "/Users/alan/projects/CHtunes/src/trainer.py", line 85, in train_one_epoch
    for batch_lst in zip(*train_loader_lst):
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alan/.pyenv/versions/3.11.7/lib/python3.11/multiprocessing/util.py", line 451, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
                                  ^^^^^^^^^
OSError: [Errno 24] Too many open files

**Comment by samuel-gauthier** [comment]
I'll have a look.

**Comment by samuel-gauthier** [comment]
I don't think so. This issue only happens when `pin_memory=True` and `persistent_workers=True` in the DataLoader parameters. We have `persistent_workers=False` (the default).

**Comment by alanngnet** [comment]
unable to duplicate even during a very large run (12 hours, 100k steps)

**Comment by alanngnet** [comment]
possibly was resolved by updating to latest pip libraries, including pytorch

**Comment by alanngnet** [comment]
Reopening due to multiple reoccurrences while running train_tune.py for many runs (more than 20?), at least on MPS.

**Comment by alanngnet** [comment]
This happens infrequently enough that I'm demoting it to P2.
